# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pizzaplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=500, unique=True)),
                ('meetup_link', models.CharField(default=None, max_length=500, unique=True)),
                ('pizza_places', models.ManyToManyField(to='pizzaplace.PizzaPlace')),
            ],
        ),
    ]
