# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='meetup_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
