# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaplace', '0001_initial'),
        ('meetup', '0002_auto_20160303_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='pizza_places',
            field=models.ManyToManyField(to='pizzaplace.PizzaPlace'),
        ),
    ]
