# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import meetup.models
import model_utils.fields


class Migration(migrations.Migration):

    replaces = [('meetup', '0003_auto_20160314_1839'), ('meetup', '0004_auto_20160314_1921'), ('meetup', '0005_auto_20160314_1922')]

    dependencies = [
        ('meetup', '0001_squashed_0002_auto_20160307_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='meetup',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='meetup_link',
            field=models.URLField(max_length=500, unique=True, validators=[meetup.models.validate_urlname, meetup.models.validate_meetup_exists]),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='meetup_link',
            field=models.URLField(default=None, max_length=500, unique=True, validators=[meetup.models.validate_urlname, meetup.models.validate_meetup_exists]),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='name',
            field=models.CharField(default=None, max_length=500, unique=True),
        ),
    ]
