# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0003_auto_20160314_1839_squashed_0005_auto_20160314_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='meetup_link',
            new_name='meetup_url',
        ),
    ]
