# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 18:39
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaplace',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='pizzaplace',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
