# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaplace', '0002_auto_20160314_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaplace',
            name='yelp_link',
            field=models.URLField(default=None, max_length=500, unique=True),
        ),
    ]
