# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import pizzaplace.models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaplace', '0003_pizzaplace_yelp_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzaplace',
            name='yelp_link',
        ),
        migrations.AddField(
            model_name='pizzaplace',
            name='yelp_url',
            field=models.URLField(default=None, max_length=500, unique=True, validators=[pizzaplace.models.validate_url, pizzaplace.models.validate_yelp_business_exists]),
        ),
    ]
